### ISSUE TITLE
Error when activating

### ISSUE THREAD

**Issue by DigitalJordan** [ColorlibHQ/shapely-companion#19]
Hey, I'm getting this error when activating this plugin.. I'm using the latest version of Shapely Theme so unsure of the issue?? Any help appreciated :)

**Plugin could not be activated because it triggered a fatal error.**

Fatal error: Cannot redeclare shapely_companion_dashboard_widget() (previously declared in /home/content/n3pnexwpnas04_data03/23/41265723/html/wp-content/plugins/shapely-companion/shapely-companion.php:33) in /home/content/n3pnexwpnas04_data03/23/41265723/html/wp-content/plugins/shapely-companion-master/shapely-companion.php on line 33

**Comment by cristianraiber** [comment]
@DigitalJordan - this is happening because you downloaded Shapely Companion plugin from GitHub. As you can see, on this line: `previously declared in /home/content/n3pnexwpnas04_data03/23/41265723/html/wp-content/plugins/shapely-companion/shapely-companion.php:33` it says that a widget, that's bundled with Shapely Companion has been already defined.

If you want to test the latest version of Shapely Companion, you should consider disabling the one you've previously installed from w.org. 

This is not an issue with the plugin.
